import type {
  AnalyticsMetric,
  ROIDataPoint,
  GDPRRecord,
  HardwareBounty,
  MicroInternship,
  ProjectValidation,
  VerificationAuditEntry,
  AdminActivityLog,
} from '../types/admin';

// ─── Analytics Metrics ──────────────────────────────────────────────────────

export const MOCK_ANALYTICS_METRICS: AnalyticsMetric[] = [
  {
    id: 'metric-1',
    label: 'Total Platform Revenue',
    value: '$2.4M',
    change: 12.5,
    trend: 'up',
    timestamp: '2025-01-15',
  },
  {
    id: 'metric-2',
    label: 'Active Users',
    value: '18,450',
    change: 8.3,
    trend: 'up',
    timestamp: '2025-01-15',
  },
  {
    id: 'metric-3',
    label: 'Conversion Rate',
    value: '4.2%',
    change: -1.2,
    trend: 'down',
    timestamp: '2025-01-15',
  },
  {
    id: 'metric-4',
    label: 'Student Engagement',
    value: '67.8%',
    change: 5.4,
    trend: 'up',
    timestamp: '2025-01-15',
  },
  {
    id: 'metric-5',
    label: 'Partner Institution Count',
    value: '142',
    change: 3.2,
    trend: 'up',
    timestamp: '2025-01-15',
  },
  {
    id: 'metric-6',
    label: 'Average Session Duration',
    value: '12m 45s',
    change: 2.1,
    trend: 'up',
    timestamp: '2025-01-15',
  },
];

// ─── ROI Chart Data ─────────────────────────────────────────────────────────

export const MOCK_ROI_DATA: ROIDataPoint[] = [
  { month: 'Jan', revenue: 240000, engagement: 62, roi: 18 },
  { month: 'Feb', revenue: 260000, engagement: 65, roi: 21 },
  { month: 'Mar', revenue: 235000, engagement: 63, roi: 19 },
  { month: 'Apr', revenue: 310000, engagement: 68, roi: 25 },
  { month: 'May', revenue: 285000, engagement: 66, roi: 23 },
  { month: 'Jun', revenue: 340000, engagement: 71, roi: 28 },
  { month: 'Jul', revenue: 380000, engagement: 74, roi: 32 },
  { month: 'Aug', revenue: 420000, engagement: 78, roi: 35 },
  { month: 'Sep', revenue: 410000, engagement: 76, roi: 34 },
  { month: 'Oct', revenue: 450000, engagement: 79, roi: 37 },
  { month: 'Nov', revenue: 480000, engagement: 82, roi: 40 },
  { month: 'Dec', revenue: 520000, engagement: 85, roi: 43 },
];

// ─── GDPR Compliance Records ────────────────────────────────────────────────

export const MOCK_GDPR_RECORDS: GDPRRecord[] = [
  {
    id: 'gdpr-001',
    userId: 'u1',
    userName: 'Alex Johnson',
    userEmail: 'alex.johnson@mit.edu',
    dataCategory: 'profile',
    status: 'active',
    createdAt: '2024-06-15',
    modifiedAt: '2025-01-10',
    retentionPeriod: '90 days',
    auditTrail: [
      {
        id: 'audit-1',
        action: 'Profile created',
        actor: 'user:u1',
        timestamp: '2024-06-15T08:00:00Z',
        details: 'Initial profile creation',
      },
      {
        id: 'audit-2',
        action: 'Profile updated',
        actor: 'user:u1',
        timestamp: '2024-12-20T14:30:00Z',
        details: 'Updated bio and skills',
      },
    ],
  },
  {
    id: 'gdpr-002',
    userId: 'u2',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@stanford.edu',
    dataCategory: 'activity',
    status: 'pending-deletion',
    createdAt: '2024-08-10',
    modifiedAt: '2025-01-12',
    retentionPeriod: '30 days',
    auditTrail: [
      {
        id: 'audit-3',
        action: 'Deletion requested',
        actor: 'user:u2',
        timestamp: '2025-01-12T10:15:00Z',
        details: 'User requested data deletion',
      },
    ],
  },
  {
    id: 'gdpr-003',
    userId: 'u3',
    userName: 'Marcus Williams',
    userEmail: 'marcus@berkeley.edu',
    dataCategory: 'connections',
    status: 'archived',
    createdAt: '2024-07-20',
    modifiedAt: '2024-11-05',
    retentionPeriod: '180 days',
    auditTrail: [
      {
        id: 'audit-4',
        action: 'Data archived',
        actor: 'admin:a1',
        timestamp: '2024-11-05T09:00:00Z',
        details: 'Account archived per retention policy',
      },
    ],
  },
  {
    id: 'gdpr-004',
    userId: 'u4',
    userName: 'TechCorp Inc',
    userEmail: 'compliance@techcorp.com',
    dataCategory: 'applications',
    status: 'active',
    createdAt: '2024-05-01',
    modifiedAt: '2025-01-15',
    retentionPeriod: '1 year',
    auditTrail: [
      {
        id: 'audit-5',
        action: 'Data access request',
        actor: 'admin:a1',
        timestamp: '2025-01-15T11:20:00Z',
        details: 'Compliance review initiated',
      },
    ],
  },
];

// ─── Hardware Bounties ──────────────────────────────────────────────────────

export const MOCK_HARDWARE_BOUNTIES: HardwareBounty[] = [
  {
    id: 'hb-001',
    title: 'ESP32 Microcontroller Integration',
    description: 'Develop drivers and libraries for ESP32 IoT platform integration',
    category: 'Microcontroller',
    value: 1500,
    status: 'published',
    applicants: 24,
    createdAt: '2024-12-10',
    createdBy: 'admin:a1',
    deadline: '2025-02-28',
  },
  {
    id: 'hb-002',
    title: 'Raspberry Pi 5 Performance Optimization',
    description: 'Optimize video processing pipeline for Raspberry Pi 5',
    category: 'Single-Board Computer',
    value: 2000,
    status: 'published',
    applicants: 18,
    createdAt: '2024-11-30',
    createdBy: 'admin:a1',
    deadline: '2025-03-15',
  },
  {
    id: 'hb-003',
    title: 'Arduino Sensor Array Development',
    description: 'Create modular sensor array library for Arduino ecosystem',
    category: 'Development Board',
    value: 1200,
    status: 'draft',
    applicants: 0,
    createdAt: '2025-01-10',
    createdBy: 'admin:a1',
    deadline: '2025-04-30',
  },
  {
    id: 'hb-004',
    title: 'STM32 Firmware Development',
    description: 'Develop custom firmware for STM32 embedded systems',
    category: 'Microcontroller',
    value: 2500,
    status: 'published',
    applicants: 31,
    createdAt: '2024-12-01',
    createdBy: 'admin:a1',
    deadline: '2025-03-31',
  },
];

// ─── Micro-Internships ──────────────────────────────────────────────────────

export const MOCK_MICRO_INTERNSHIPS: MicroInternship[] = [
  {
    id: 'mi-001',
    title: 'Backend API Development - Node.js',
    description: 'Build RESTful APIs for our platform',
    company: 'TechCorp Inc',
    duration: '4 weeks',
    compensation: '$1,200',
    status: 'published',
    applicants: 42,
    createdAt: '2024-12-15',
    deadline: '2025-02-15',
  },
  {
    id: 'mi-002',
    title: 'React Component Library Refactor',
    description: 'Modernize and refactor existing component library',
    company: 'Stackform',
    duration: '6 weeks',
    compensation: '$1,800',
    status: 'published',
    applicants: 35,
    createdAt: '2024-12-20',
    deadline: '2025-03-01',
  },
  {
    id: 'mi-003',
    title: 'Data Analytics Dashboard',
    description: 'Create real-time analytics dashboards using D3.js',
    company: 'DataStream Labs',
    duration: '3 weeks',
    compensation: '$900',
    status: 'completed',
    applicants: 28,
    createdAt: '2024-11-01',
    deadline: '2025-01-15',
  },
  {
    id: 'mi-004',
    title: 'Mobile App Testing & QA',
    description: 'Comprehensive testing and QA for iOS app',
    company: 'MobileFirst',
    duration: '4 weeks',
    compensation: '$1,100',
    status: 'draft',
    applicants: 0,
    createdAt: '2025-01-05',
    deadline: '2025-03-20',
  },
];

// ─── Project Validations ────────────────────────────────────────────────────

export const MOCK_PROJECT_VALIDATIONS: ProjectValidation[] = [
  {
    id: 'pv-001',
    projectId: 'proj-001',
    projectTitle: 'AI-Powered Recommendation Engine',
    authorName: 'Alex Johnson',
    submittedAt: '2025-01-10T14:30:00Z',
    validatedAt: '2025-01-12T09:15:00Z',
    validatedBy: 'Dr. Sarah Chen',
    status: 'approved',
    validationNotes: 'Excellent technical implementation with clear documentation.',
    attachments: ['proposal.pdf', 'technical_spec.md'],
  },
  {
    id: 'pv-002',
    projectId: 'proj-002',
    projectTitle: 'Cloud Infrastructure Automation',
    authorName: 'Marcus Williams',
    submittedAt: '2025-01-14T10:00:00Z',
    validatedAt: '2025-01-15T16:45:00Z',
    validatedBy: 'Prof. James Rodriguez',
    status: 'approved',
    validationNotes: 'Strong DevOps practices. Minor documentation improvements suggested.',
    attachments: ['architecture_diagram.png', 'deployment_guide.md'],
  },
  {
    id: 'pv-003',
    projectId: 'proj-003',
    projectTitle: 'Blockchain Voting System',
    authorName: 'Emma Thompson',
    submittedAt: '2025-01-13T11:20:00Z',
    status: 'needs-revision',
    validationNotes: 'Please address security concerns in smart contract review. See detailed comments.',
    attachments: ['contract_audit.pdf'],
  },
  {
    id: 'pv-004',
    projectId: 'proj-004',
    projectTitle: 'Real-time Collaboration Platform',
    authorName: 'David Kim',
    submittedAt: '2025-01-15T09:00:00Z',
    status: 'pending',
    validationNotes: '',
    attachments: [],
  },
];

// ─── Verification Audit Trail ───────────────────────────────────────────────

export const MOCK_VERIFICATION_AUDIT_TRAIL: VerificationAuditEntry[] = [
  {
    id: 'audit-v-001',
    entityType: 'project',
    entityId: 'proj-001',
    entityName: 'AI Recommendation Engine',
    action: 'verified',
    reviewedBy: 'Dr. Sarah Chen',
    timestamp: '2025-01-12T09:15:00Z',
    severity: 'low',
  },
  {
    id: 'audit-v-002',
    entityType: 'user',
    entityId: 'u1',
    entityName: 'Alex Johnson',
    action: 'flagged',
    reviewedBy: 'Admin Portal',
    timestamp: '2025-01-14T14:30:00Z',
    reason: 'Multiple copyright violation reports',
    severity: 'high',
  },
  {
    id: 'audit-v-003',
    entityType: 'institution',
    entityId: 'inst-001',
    entityName: 'MIT',
    action: 'verified',
    reviewedBy: 'Dr. Sarah Chen',
    timestamp: '2025-01-10T08:00:00Z',
    severity: 'low',
  },
  {
    id: 'audit-v-004',
    entityType: 'project',
    entityId: 'proj-003',
    entityName: 'Blockchain Voting System',
    action: 'flagged',
    reviewedBy: 'Security Team',
    timestamp: '2025-01-15T11:20:00Z',
    reason: 'Security vulnerabilities detected',
    severity: 'high',
  },
];

// ─── Admin Activity Logs ────────────────────────────────────────────────────

export const MOCK_ADMIN_ACTIVITY_LOGS: AdminActivityLog[] = [
  {
    id: 'log-001',
    adminId: 'admin:a1',
    adminName: 'System Administrator',
    action: 'Created new hardware bounty',
    resourceType: 'HardwareBounty',
    resourceId: 'hb-004',
    timestamp: '2025-01-15T10:30:00Z',
    status: 'success',
  },
  {
    id: 'log-002',
    adminId: 'admin:a1',
    adminName: 'System Administrator',
    action: 'Updated project validation status',
    resourceType: 'ProjectValidation',
    resourceId: 'pv-003',
    timestamp: '2025-01-15T11:20:00Z',
    changes: { status: 'needs-revision' },
    status: 'success',
  },
  {
    id: 'log-003',
    adminId: 'admin:a1',
    adminName: 'System Administrator',
    action: 'User data deletion request processed',
    resourceType: 'GDPRRecord',
    resourceId: 'gdpr-002',
    timestamp: '2025-01-15T14:45:00Z',
    status: 'success',
  },
  {
    id: 'log-004',
    adminId: 'admin:a1',
    adminName: 'System Administrator',
    action: 'Failed to update micro-internship',
    resourceType: 'MicroInternship',
    resourceId: 'mi-002',
    timestamp: '2025-01-15T15:10:00Z',
    status: 'failed',
  },
];
