import type {
  User, Post, Job, Project, Bounty,
  LectureMaterial, StudentInitiative, QAChannel, Deadline,
  Badge, Achievement, Certificate, Community, CommunityEvent, NewsArticle,
} from '../types';

// ─── Badges catalogue ──────────────────────────────────────────────────────

export const ALL_BADGES: Badge[] = [
  // Contribution
  { id: 'bg-first-post',      name: 'First Post',        description: 'Published your first post on the platform',                  icon: '✍️',  tier: 'bronze',   category: 'contribution' },
  { id: 'bg-bounty-hunter',   name: 'Bounty Hunter',     description: 'Applied to and completed your first bounty',                 icon: '🎯',  tier: 'silver',   category: 'contribution' },
  { id: 'bg-eagle-scout',     name: 'Eagle Scout',       description: 'Completed 5 or more bounties',                               icon: '🦅',  tier: 'gold',     category: 'contribution' },
  { id: 'bg-top-solver',      name: 'Top Solver',        description: 'Ranked #1 on the monthly leaderboard',                       icon: '🏆',  tier: 'platinum', category: 'contribution' },
  { id: 'bg-code-wizard',     name: 'Code Wizard',       description: 'Submitted a bounty that was accepted without revisions',      icon: '🧙',  tier: 'gold',     category: 'contribution' },
  // Community
  { id: 'bg-community-start', name: 'Founder',           description: 'Created a community with 50+ members',                       icon: '🏛️',  tier: 'silver',   category: 'community' },
  { id: 'bg-connector',       name: 'Connector',         description: 'Member of 5 or more communities simultaneously',             icon: '🔗',  tier: 'bronze',   category: 'community' },
  { id: 'bg-event-host',      name: 'Event Host',        description: 'Organised a workshop or talk with 20+ attendees',            icon: '🎤',  tier: 'silver',   category: 'community' },
  { id: 'bg-helpful',         name: 'Most Helpful',      description: 'Answered 10 open Q&A questions',                             icon: '🙌',  tier: 'gold',     category: 'community' },
  // Learning
  { id: 'bg-news-hound',      name: 'News Hound',        description: 'Read 20 electronics industry news articles',                 icon: '📰',  tier: 'bronze',   category: 'learning' },
  { id: 'bg-cert-pro',        name: 'Certified Pro',     description: 'Earned your first professional certificate on the platform',  icon: '📜',  tier: 'silver',   category: 'learning' },
  { id: 'bg-deep-diver',      name: 'Deep Diver',        description: 'Completed all materials for a full course track',            icon: '🤿',  tier: 'gold',     category: 'learning' },
  // Achievement
  { id: 'bg-rising-star',     name: 'Rising Star',       description: 'Earned 500 XP within your first 30 days',                   icon: '⭐',  tier: 'silver',   category: 'achievement' },
  { id: 'bg-innovator',       name: 'Innovator',         description: 'Project received institutional endorsement',                  icon: '💡',  tier: 'gold',     category: 'achievement' },
  { id: 'bg-veteran',         name: 'Veteran',           description: 'Active on the platform for over 1 year',                     icon: '🎖️',  tier: 'silver',   category: 'achievement' },
  // Special
  { id: 'bg-og',              name: 'OG',                description: 'Joined during the platform beta',                            icon: '🌟',  tier: 'platinum', category: 'special' },
  { id: 'bg-mentor',          name: 'Mentor',            description: 'Successfully mentored 3+ students to completion',            icon: '🧑‍🏫', tier: 'gold',     category: 'special' },
  { id: 'bg-hardware-hacker', name: 'Hardware Hacker',   description: 'Built and shipped a physical electronics prototype',         icon: '🔧',  tier: 'silver',   category: 'special' },
];

const getBadgeById = (id: string): Badge => {
  const b = ALL_BADGES.find(b => b.id === id)!;
  return b;
};

// ─── Users ─────────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    role: 'student',
    name: 'Priya Nair',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    headline: 'CS Senior @ Carnegie Mellon · Full-stack & ML',
    location: 'Pittsburgh, PA',
    university: 'Carnegie Mellon University',
    graduationYear: 2026,
    skills: ['TypeScript', 'React', 'Python', 'PyTorch', 'PostgreSQL'],
    followersCount: 412,
    followingCount: 188,
    bio: 'Building things at the intersection of systems and intelligence. Open to SWE and ML internships for Summer 2026.',
    joinedAt: '2024-09-01',
    points: 1840,
    interests: ['distributed-systems', 'machine-learning', 'open-source', 'power-electronics'],
    badges: [
      { ...getBadgeById('bg-og'),           earnedAt: '2024-09-01' },
      { ...getBadgeById('bg-first-post'),   earnedAt: '2024-09-03' },
      { ...getBadgeById('bg-bounty-hunter'),earnedAt: '2025-02-10' },
      { ...getBadgeById('bg-rising-star'),  earnedAt: '2024-10-01' },
      { ...getBadgeById('bg-innovator'),    earnedAt: '2026-03-15' },
      { ...getBadgeById('bg-connector'),    earnedAt: '2026-01-20' },
    ],
    achievements: [
      { id: 'ach1', name: 'Bounty Accepted',      description: 'Carbon Footprint Calculator bounty accepted by GreenPulse', icon: '🎯', points: 300, unlockedAt: '2026-03-01T00:00:00Z' },
      { id: 'ach2', name: 'VoltForge Endorsed',   description: 'Team VoltForge project received institutional endorsement',  icon: '✅', points: 500, unlockedAt: '2026-05-20T00:00:00Z' },
      { id: 'ach3', name: '400 Followers',         description: 'Reached 400 followers on the platform',                     icon: '👥', points: 200, unlockedAt: '2026-04-01T00:00:00Z' },
      { id: 'ach4', name: 'Q&A Helper',            description: 'Answered 5 open Q&A questions this week',                   icon: '💬', points: 150, unlockedAt: '2026-06-15T00:00:00Z' },
    ],
    certificates: [
      { id: 'cert1', title: 'Power Electronics Fundamentals', issuer: 'TU Munich · Prof. Elena Hartmann', issuedAt: '2026-06-01', credentialId: 'TUM-EE401-2026-U1', skills: ['MOSFET', 'Gate Drive', 'Magnetics', 'Thermal Design'], badgeUrl: '🏅' },
    ],
  },
  {
    id: 'u2',
    role: 'student',
    name: 'Marcus Webb',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    headline: 'Product Design · UC San Diego · 2025',
    location: 'San Diego, CA',
    university: 'UC San Diego',
    graduationYear: 2025,
    skills: ['Figma', 'React', 'CSS', 'User Research', 'Prototyping'],
    followersCount: 289,
    followingCount: 143,
    bio: 'Designer who codes. Interested in how interfaces shape behavior at scale.',
    joinedAt: '2024-01-15',
    points: 920,
    interests: ['ux-design', 'product', 'prototyping', 'accessibility'],
    badges: [
      { ...getBadgeById('bg-og'),           earnedAt: '2024-01-15' },
      { ...getBadgeById('bg-first-post'),   earnedAt: '2024-01-20' },
      { ...getBadgeById('bg-veteran'),      earnedAt: '2025-01-15' },
      { ...getBadgeById('bg-news-hound'),   earnedAt: '2026-04-01' },
    ],
    achievements: [
      { id: 'ach5', name: 'Storybook Award',    description: 'Aria Design System featured in platform showcase',     icon: '📚', points: 250, unlockedAt: '2026-02-10T00:00:00Z' },
      { id: 'ach6', name: 'Bounty Applied',     description: 'Applied to Stackform onboarding redesign bounty',      icon: '🎯', points: 50,  unlockedAt: '2026-06-12T00:00:00Z' },
    ],
    certificates: [],
  },
  {
    id: 'u3',
    role: 'student',
    name: 'Aisha Kamara',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    headline: 'Data Science @ UT Austin · Class of 2026',
    location: 'Austin, TX',
    university: 'University of Texas at Austin',
    graduationYear: 2026,
    skills: ['Python', 'SQL', 'Tableau', 'R', 'Machine Learning'],
    followersCount: 174,
    followingCount: 96,
    bio: 'Turning messy data into clear decisions. Passionate about climate tech and civic data.',
    joinedAt: '2024-03-10',
    points: 610,
    interests: ['data-science', 'climate', 'geospatial', 'open-source'],
    badges: [
      { ...getBadgeById('bg-first-post'),   earnedAt: '2024-03-15' },
      { ...getBadgeById('bg-news-hound'),   earnedAt: '2025-11-01' },
      { ...getBadgeById('bg-connector'),    earnedAt: '2026-02-01' },
    ],
    achievements: [
      { id: 'ach7', name: 'AirView Featured', description: 'AirView Austin project featured in community spotlight', icon: '🌿', points: 300, unlockedAt: '2026-06-14T00:00:00Z' },
      { id: 'ach8', name: 'Data Deep Diver',  description: 'Published a Jupyter notebook with reproducible analysis',icon: '📊', points: 150, unlockedAt: '2026-03-01T00:00:00Z' },
    ],
    certificates: [],
  },
  {
    id: 'u4',
    role: 'company',
    name: 'Meridian Labs',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=ML&backgroundColor=2563eb',
    headline: 'Developer tools for the next generation of engineers',
    location: 'San Francisco, CA',
    industry: 'Developer Tools / SaaS',
    size: '51–200 employees',
    website: 'https://meridianlabs.dev',
    followersCount: 3820,
    followingCount: 41,
    bio: 'We build infrastructure that helps engineering teams ship faster. Always looking for curious people.',
    joinedAt: '2023-06-01',
    points: 2400,
    badges: [
      { ...getBadgeById('bg-og'),             earnedAt: '2023-06-01' },
      { ...getBadgeById('bg-helpful'),         earnedAt: '2024-06-01' },
      { ...getBadgeById('bg-event-host'),      earnedAt: '2025-03-01' },
      { ...getBadgeById('bg-top-solver'),      earnedAt: '2026-01-01' },
    ],
    achievements: [],
    certificates: [],
  },
  {
    id: 'u5',
    role: 'company',
    name: 'GreenPulse',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=GP&backgroundColor=16a34a',
    headline: 'Climate tech powering a sustainable future',
    location: 'Boston, MA',
    industry: 'Climate Tech',
    size: '11–50 employees',
    website: 'https://greenpulse.io',
    followersCount: 1240,
    followingCount: 22,
    bio: 'Our platform helps cities track and reduce carbon emissions in real time.',
    joinedAt: '2023-11-15',
    points: 1180,
    badges: [
      { ...getBadgeById('bg-innovator'),  earnedAt: '2024-05-01' },
      { ...getBadgeById('bg-connector'),  earnedAt: '2025-01-01' },
    ],
    achievements: [],
    certificates: [],
  },
  {
    id: 'u6',
    role: 'company',
    name: 'Stackform',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=SF&backgroundColor=7c3aed',
    headline: 'No-code infrastructure, built for teams',
    location: 'New York, NY',
    industry: 'Enterprise SaaS',
    size: '201–500 employees',
    website: 'https://stackform.com',
    followersCount: 6110,
    followingCount: 80,
    bio: 'Stackform replaces your tangled internal tools with one coherent platform. Used by 4,000+ teams worldwide.',
    joinedAt: '2022-04-10',
    points: 3250,
    badges: [
      { ...getBadgeById('bg-og'),           earnedAt: '2022-04-10' },
      { ...getBadgeById('bg-top-solver'),   earnedAt: '2023-01-01' },
      { ...getBadgeById('bg-event-host'),   earnedAt: '2023-06-01' },
      { ...getBadgeById('bg-eagle-scout'),  earnedAt: '2024-03-01' },
      { ...getBadgeById('bg-code-wizard'),  earnedAt: '2024-08-01' },
    ],
    achievements: [],
    certificates: [],
  },
  {
    id: 'u7',
    role: 'educator',
    name: 'Prof. Elena Hartmann',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    headline: 'Chair of Electrical Engineering · TU Munich',
    location: 'Munich, Germany',
    university: 'Technical University of Munich',
    followersCount: 1847,
    followingCount: 63,
    bio: 'Professor and department chair overseeing 14 research groups. Bridging academia and industry through student-industry collaboration programmes since 2018.',
    joinedAt: '2023-10-01',
    points: 2900,
    badges: [
      { ...getBadgeById('bg-mentor'),        earnedAt: '2024-06-01' },
      { ...getBadgeById('bg-event-host'),    earnedAt: '2024-09-01' },
      { ...getBadgeById('bg-deep-diver'),    earnedAt: '2025-01-01' },
      { ...getBadgeById('bg-cert-pro'),      earnedAt: '2025-06-01' },
      { ...getBadgeById('bg-helpful'),       earnedAt: '2026-01-01' },
      { ...getBadgeById('bg-community-start'), earnedAt: '2024-03-01' },
    ],
    achievements: [
      { id: 'ach9',  name: '100 Certificates Issued', description: 'Issued over 100 student certificates through the platform', icon: '📜', points: 1000, unlockedAt: '2026-05-01T00:00:00Z' },
      { id: 'ach10', name: 'Research Spotlight',      description: 'Featured in the monthly educator spotlight',                icon: '🔬', points: 500,  unlockedAt: '2026-03-01T00:00:00Z' },
    ],
    certificates: [],
  },
  {
    id: 'admin-001',
    role: 'corporate_admin',
    name: 'System Administrator',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=SA&backgroundColor=1f2937',
    headline: 'Platform Administrator',
    location: 'Virtual',
    followersCount: 0,
    followingCount: 0,
    bio: 'Platform administration and oversight.',
    joinedAt: '2024-01-01',
    points: 0,
    badges: [],
    achievements: [],
    certificates: [],
  },
];

export const STUDENT_USERS = MOCK_USERS.filter(u => u.role === 'student');
export const COMPANY_USERS = MOCK_USERS.filter(u => u.role === 'company');
export const EDUCATOR_USERS = MOCK_USERS.filter(u => u.role === 'educator');

export const getUserById = (id: string): User | undefined =>
  MOCK_USERS.find(u => u.id === id);

// ─── Posts ─────────────────────────────────────────────────────────────────

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    authorId: 'u4',
    type: 'text',
    content:
      "We're opening 3 summer internship spots for backend engineers. If you've shipped something real and enjoy working close to the metal — apply. We move fast and give interns real ownership.\n\n👇 Link in the Jobs tab.",
    likes: 184,
    likedBy: ['u1', 'u3'],
    comments: [
      { id: 'c1', authorId: 'u1', content: 'Just applied! Love what you all are building with the CI pipeline tooling.', createdAt: '2026-06-18T10:22:00Z', likes: 4 },
    ],
    shares: 27,
    createdAt: '2026-06-18T08:00:00Z',
    tags: ['hiring', 'internship', 'backend'],
  },
  {
    id: 'p2',
    authorId: 'u1',
    type: 'image',
    content:
      'Shipped my final project for Advanced Systems this semester — a distributed key-value store written in Go with Raft consensus. 4 weeks, a lot of late nights, and exactly zero memory leaks (eventually).',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    likes: 312,
    likedBy: ['u2', 'u4', 'u5'],
    comments: [
      { id: 'c2', authorId: 'u4', content: 'This is impressive work — have you considered Go for backend roles? We use it heavily.', createdAt: '2026-06-17T14:05:00Z', likes: 7 },
      { id: 'c3', authorId: 'u2', content: 'Congrats Priya!! 🎉', createdAt: '2026-06-17T14:30:00Z', likes: 2 },
    ],
    shares: 44,
    createdAt: '2026-06-17T12:00:00Z',
    tags: ['Go', 'distributed-systems', 'projects'],
  },
  {
    id: 'p3',
    authorId: 'u5',
    type: 'link',
    content:
      "We just published our 2026 Climate Tech Talent Report. One finding that stood out: 68% of climate startups say hiring is their #1 bottleneck. Platforms like this one are part of the solution.",
    linkPreview: {
      url: 'https://greenpulse.io/report-2026',
      title: '2026 Climate Tech Talent Report — GreenPulse',
      description: 'Key hiring trends, salary benchmarks, and the skills gap facing climate-focused companies.',
      imageUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800&q=80',
    },
    likes: 97,
    likedBy: ['u3'],
    comments: [],
    shares: 33,
    createdAt: '2026-06-16T09:30:00Z',
    tags: ['climate', 'hiring', 'report'],
  },
  {
    id: 'p4',
    authorId: 'u2',
    type: 'text',
    content:
      "Hot take: most onboarding flows treat first-time users like they already know what the product does. The best ones I've seen start with a single question — 'what are you trying to accomplish?' — and build from there.\n\nWhat's the most thoughtful onboarding you've encountered?",
    likes: 228,
    likedBy: ['u1', 'u6'],
    comments: [
      { id: 'c4', authorId: 'u6', content: "Notion's early onboarding was the gold standard for us — they got out of the way immediately.", createdAt: '2026-06-15T20:10:00Z', likes: 11 },
    ],
    shares: 19,
    createdAt: '2026-06-15T18:00:00Z',
    tags: ['design', 'ux', 'product'],
  },
  {
    id: 'p5',
    authorId: 'u3',
    type: 'text',
    content:
      "Built a dashboard in a weekend that tracks Austin's real-time air quality + overlays it against traffic and weather data. Surprised by how strongly particulate matter correlates with Tuesday morning rush hour specifically.\n\nOpen-sourcing it next week.",
    likes: 157,
    likedBy: ['u1', 'u5'],
    comments: [],
    shares: 22,
    createdAt: '2026-06-14T11:00:00Z',
    tags: ['data', 'climate', 'open-source'],
  },
  {
    id: 'p6',
    authorId: 'u6',
    type: 'text',
    content:
      "We crossed 4,000 teams on Stackform this month. When we started, our bet was that internal tooling was broken in a way nobody wanted to talk about. Turns out, a lot of people wanted to talk about it.\n\nHuge thanks to the engineering team and to every team that gave us candid feedback early.",
    likes: 541,
    likedBy: ['u2'],
    comments: [
      { id: 'c5', authorId: 'u2', content: "Big congrats! Stackform's component library was genuinely the best DX I've used for internal tools.", createdAt: '2026-06-13T16:00:00Z', likes: 14 },
    ],
    shares: 88,
    createdAt: '2026-06-13T14:00:00Z',
    tags: ['milestone', 'product'],
  },
];

// ─── Jobs ──────────────────────────────────────────────────────────────────

export const MOCK_JOBS: Job[] = [
  {
    id: 'j1',
    companyId: 'u4',
    title: 'Backend Engineering Intern',
    location: 'San Francisco, CA (Hybrid)',
    type: 'Internship',
    salary: '$45–55 / hr',
    description: 'Join our core platform team to help build the infrastructure that thousands of engineering teams rely on daily.',
    requirements: [
      'Enrolled in a CS or related degree program',
      'Proficiency in Go, Rust, or C++',
      'Familiarity with distributed systems concepts',
      'Strong debugging and systems-thinking skills',
    ],
    tags: ['Go', 'Rust', 'Distributed Systems', 'Backend', 'Internship'],
    postedAt: '2026-06-18T08:00:00Z',
    applicationCount: 38,
    appliedBy: [],
  },
  {
    id: 'j2',
    companyId: 'u5',
    title: 'Data Engineer (Full-time)',
    location: 'Boston, MA (On-site)',
    type: 'Full-time',
    salary: '$120,000–$145,000',
    description: 'GreenPulse is hiring a Data Engineer to expand our real-time emissions tracking pipeline.',
    requirements: [
      '2+ years of data engineering experience',
      'Strong Python and SQL',
      'Experience with streaming systems (Kafka, Flink, or similar)',
      'Passion for climate or civic tech a strong plus',
    ],
    tags: ['Python', 'SQL', 'Kafka', 'Data Engineering', 'Climate'],
    postedAt: '2026-06-15T09:00:00Z',
    applicationCount: 24,
    appliedBy: [],
  },
  {
    id: 'j3',
    companyId: 'u6',
    title: 'Product Design Intern',
    location: 'New York, NY (Hybrid)',
    type: 'Internship',
    salary: '$38–46 / hr',
    description: "Stackform is looking for a product design intern to join the platform experience team.",
    requirements: [
      'Portfolio demonstrating product design craft',
      'Proficiency in Figma',
      'Experience with user research or usability testing',
      'Can articulate design decisions clearly',
    ],
    tags: ['Figma', 'Product Design', 'UX Research', 'Internship'],
    postedAt: '2026-06-12T11:00:00Z',
    applicationCount: 61,
    appliedBy: [],
  },
  {
    id: 'j4',
    companyId: 'u4',
    title: 'Developer Advocate (Contract)',
    location: 'Remote',
    type: 'Contract',
    salary: '$80–100 / hr',
    description: 'Help us reach developer communities through technical content, talks, and open-source contributions.',
    requirements: [
      'Strong technical writing and communication',
      'Active presence in developer communities',
      'Experience building demo projects or tutorials',
      'Comfortable with public speaking / streaming',
    ],
    tags: ['DevRel', 'Technical Writing', 'Open Source', 'Remote'],
    postedAt: '2026-06-10T10:00:00Z',
    applicationCount: 17,
    appliedBy: [],
  },
  {
    id: 'j5',
    companyId: 'u5',
    title: 'Climate Data Analyst Intern',
    location: 'Remote',
    type: 'Internship',
    salary: '$28–35 / hr',
    description: 'Analyze emissions datasets, build reporting pipelines, and help surface insights that city partners use to make policy decisions.',
    requirements: [
      'Python and SQL proficiency',
      'Experience with data visualization (Tableau, Plotly, or similar)',
      'Interest in climate policy or sustainability',
      'Strong written communication for stakeholder reports',
    ],
    tags: ['Python', 'Data Analysis', 'Climate', 'Internship', 'Remote'],
    postedAt: '2026-06-08T08:00:00Z',
    applicationCount: 49,
    appliedBy: [],
  },
];

// ─── Bounties ──────────────────────────────────────────────────────────────

export const MOCK_BOUNTIES: Bounty[] = [
  {
    id: 'b1',
    companyId: 'u4',
    title: 'Build a CI/CD Pipeline Visualizer Widget',
    description: 'Meridian Labs is looking for a developer to build an embeddable React widget that visualizes CI/CD pipeline runs in real time.',
    submissionRequirements: 'Submit a GitHub repo with the widget source, a README with usage instructions, and a live Stackblitz or CodeSandbox demo.',
    requirements: ['Strong React + TypeScript skills', 'Experience with SVG or canvas-based rendering', 'Understanding of CI/CD concepts', 'Ability to write clean, documented code'],
    tags: ['React', 'TypeScript', 'D3', 'SVG', 'CI/CD', 'npm'],
    reward: '$750 cash',
    duration: '2–3 weeks',
    deadline: '2026-07-15T23:59:00Z',
    postedAt: '2026-06-18T09:00:00Z',
    applicationCount: 12,
    appliedBy: [],
    status: 'open',
  },
  {
    id: 'b2',
    companyId: 'u4',
    title: 'Write a 5-Part Tutorial Series on Distributed Tracing',
    description: 'We want a well-structured, technically accurate tutorial series explaining distributed tracing from first principles through to production implementation.',
    submissionRequirements: 'Submit all 5 articles in Markdown format with working code samples in a companion GitHub repo.',
    requirements: ['Strong technical writing', 'Backend engineering experience (Go or Python)', 'Hands-on experience with OpenTelemetry', 'Ability to explain distributed systems concepts'],
    tags: ['Technical Writing', 'Go', 'Python', 'OpenTelemetry', 'Distributed Systems'],
    reward: '$500 + byline credit',
    duration: '3–4 weeks',
    deadline: '2026-07-25T23:59:00Z',
    postedAt: '2026-06-15T10:00:00Z',
    applicationCount: 8,
    appliedBy: [],
    status: 'open',
  },
  {
    id: 'b3',
    companyId: 'u5',
    title: 'Carbon Footprint Calculator — React Component',
    description: 'GreenPulse needs a standalone React component that lets users estimate their household carbon footprint.',
    submissionRequirements: 'Deliver a published npm package with full TypeScript types, unit tests (>80% coverage), and Storybook stories.',
    requirements: ['React + TypeScript', 'Familiarity with carbon accounting', 'Component design skills', 'Jest or Vitest for testing'],
    tags: ['React', 'TypeScript', 'Storybook', 'Climate', 'Accessibility'],
    reward: '$600 cash',
    duration: '3 weeks',
    deadline: '2026-07-20T23:59:00Z',
    postedAt: '2026-06-14T11:00:00Z',
    applicationCount: 19,
    appliedBy: ['u1'],
    status: 'open',
  },
  {
    id: 'b4',
    companyId: 'u5',
    title: 'Urban Tree Coverage vs Urban Heat Island — Data Analysis',
    description: 'We have datasets from 12 US cities covering satellite-derived tree canopy coverage and surface temperature anomalies.',
    submissionRequirements: 'Deliver a Jupyter notebook with reproducible analysis and an executive summary.',
    requirements: ['Python (pandas, geopandas, statsmodels)', 'Experience with geospatial data', 'Statistical literacy', 'Clear data visualization'],
    tags: ['Python', 'Data Analysis', 'GIS', 'Climate', 'Statistics'],
    reward: '$400 + co-authorship on GreenPulse blog post',
    duration: '2–3 weeks',
    deadline: '2026-07-10T23:59:00Z',
    postedAt: '2026-06-10T08:00:00Z',
    applicationCount: 7,
    appliedBy: [],
    status: 'reviewing',
  },
  {
    id: 'b5',
    companyId: 'u6',
    title: 'Redesign Stackform Onboarding Flow (UX + Hi-Fi)',
    description: 'Our current onboarding drop-off rate at step 3 is 54%. We need a product designer to audit and redesign.',
    submissionRequirements: 'Deliver: (1) 2-page audit doc, (2) hi-fi Figma prototype, (3) 10-min Loom walkthrough.',
    requirements: ['Strong portfolio in product/UX design', 'Proficiency in Figma', 'Ability to conduct heuristic evaluation', 'Experience with SaaS onboarding'],
    tags: ['Figma', 'UX Design', 'Product Design', 'Onboarding', 'SaaS'],
    reward: '$800 cash',
    duration: '3–4 weeks',
    deadline: '2026-07-28T23:59:00Z',
    postedAt: '2026-06-12T14:00:00Z',
    applicationCount: 31,
    appliedBy: ['u2'],
    status: 'open',
  },
  {
    id: 'b6',
    companyId: 'u6',
    title: 'TypeScript REST API Client SDK',
    description: 'Stackform is publishing a public API and needs a first-class TypeScript SDK to go with it.',
    submissionRequirements: 'Deliver the SDK as a published npm package with full TypeScript types and 90%+ test coverage.',
    requirements: ['Deep TypeScript expertise', 'Experience building npm packages', 'Understanding of REST API design', 'Familiarity with fetch / axios'],
    tags: ['TypeScript', 'SDK', 'REST API', 'npm', 'OpenAPI'],
    reward: '$1,000 cash',
    duration: '4–6 weeks',
    deadline: '2026-08-10T23:59:00Z',
    postedAt: '2026-06-08T10:00:00Z',
    applicationCount: 15,
    appliedBy: [],
    status: 'open',
  },
];

export const getBountyById = (id: string): Bounty | undefined =>
  MOCK_BOUNTIES.find(b => b.id === id);

// ─── Projects ──────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'pr1',
    authorId: 'u1',
    title: 'RaftKV — Distributed Key-Value Store',
    description: 'A fault-tolerant distributed key-value store built on the Raft consensus algorithm in Go.',
    tags: ['Go', 'Distributed Systems', 'Raft', 'GCP'],
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    repoUrl: 'https://github.com/priya/raftkv',
    createdAt: '2026-06-01T00:00:00Z',
    likes: 88,
    likedBy: ['u2', 'u4'],
  },
  {
    id: 'pr2',
    authorId: 'u2',
    title: 'Aria Design System',
    description: 'An accessible, token-based component library built in React + TypeScript. Includes 40+ components.',
    tags: ['React', 'TypeScript', 'Figma', 'Accessibility', 'Storybook'],
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    repoUrl: 'https://github.com/marcuswebb/aria-ds',
    liveUrl: 'https://aria-ds.vercel.app',
    createdAt: '2026-05-10T00:00:00Z',
    likes: 143,
    likedBy: ['u1', 'u6'],
  },
  {
    id: 'pr3',
    authorId: 'u3',
    title: 'AirView Austin',
    description: 'Real-time dashboard visualizing Austin air quality index and correlations with traffic and weather data.',
    tags: ['Python', 'React', 'Plotly', 'PostgreSQL', 'Climate'],
    imageUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800&q=80',
    repoUrl: 'https://github.com/aishakamara/airview',
    liveUrl: 'https://airview.vercel.app',
    createdAt: '2026-06-14T00:00:00Z',
    likes: 72,
    likedBy: ['u1', 'u5'],
  },
  {
    id: 'pr4',
    authorId: 'u1',
    title: 'NoteSync — Local-First Notes App',
    description: 'A local-first Markdown notes app with real-time peer-to-peer sync using CRDTs (Yjs).',
    tags: ['TypeScript', 'Yjs', 'CRDTs', 'Electron', 'Markdown'],
    repoUrl: 'https://github.com/priya/notesync',
    createdAt: '2026-04-20T00:00:00Z',
    likes: 54,
    likedBy: ['u4'],
  },
  {
    id: 'pr5',
    authorId: 'u2',
    title: 'Onboard.fyi — Onboarding UX Teardowns',
    description: 'A curated collection of annotated onboarding flow breakdowns from 30+ products.',
    tags: ['UX Research', 'Product Design', 'Case Studies'],
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    liveUrl: 'https://onboard.fyi',
    createdAt: '2026-03-05T00:00:00Z',
    likes: 201,
    likedBy: ['u1', 'u3', 'u6'],
  },
];

// ─── Lecture Materials ─────────────────────────────────────────────────────

export const MOCK_LECTURE_MATERIALS: LectureMaterial[] = [
  { id: 'lm1', authorId: 'u7', title: 'Week 9 — Inverter Topologies & Gate Drive Circuits', course: 'EE401 — Power Electronics', type: 'slides',    uploadedAt: '2026-06-17T09:00:00Z', downloads: 214, fileSize: '6.1 MB',  tags: ['MOSFET', 'gate-drive', 'inverters'],    published: true  },
  { id: 'lm2', authorId: 'u7', title: 'Lab 4 Handout — Half-Bridge Converter Bench Setup',  course: 'EE401 — Power Electronics', type: 'lab',       uploadedAt: '2026-06-15T14:30:00Z', downloads: 198, fileSize: '2.3 MB',  tags: ['half-bridge', 'bench', 'lab'],          published: true  },
  { id: 'lm3', authorId: 'u7', title: 'Lecture Notes — Thermal Management in High-Power',   course: 'EE401 — Power Electronics', type: 'notes',     uploadedAt: '2026-06-12T11:00:00Z', downloads: 156, fileSize: '1.8 MB',  tags: ['thermal', 'heatsinks'],                 published: true  },
  { id: 'lm4', authorId: 'u7', title: 'Week 8 — Magnetics Design: Transformers & Inductors',course: 'EE401 — Power Electronics', type: 'slides',    uploadedAt: '2026-06-10T09:00:00Z', downloads: 231, fileSize: '8.4 MB',  tags: ['magnetics', 'transformers', 'inductors'],published: true  },
  { id: 'lm5', authorId: 'u7', title: 'Recorded Lecture — PFC & EMC Compliance Basics',     course: 'EE501 — Power Systems Advanced', type: 'recording', uploadedAt: '2026-06-08T16:00:00Z', downloads: 87,  fileSize: '312 MB', tags: ['PFC', 'EMC', 'compliance'],             published: true  },
  { id: 'lm6', authorId: 'u7', title: 'Draft: Week 10 — SiC & GaN Wide-Bandgap Devices',    course: 'EE401 — Power Electronics', type: 'slides',    uploadedAt: '2026-06-19T08:00:00Z', downloads: 0,   fileSize: '5.7 MB',  tags: ['SiC', 'GaN', 'wide-bandgap'],           published: false },
];

// ─── Student Initiatives ───────────────────────────────────────────────────

export const MOCK_INITIATIVES: StudentInitiative[] = [
  { id: 'si1', teamName: 'VoltForge',  memberNames: ['Priya Nair', 'Jonas Becker', 'Amara Osei'],          projectTitle: 'Bidirectional EV Charger — 3.3 kW Prototype',          description: 'Designing a vehicle-to-grid capable 3.3 kW bidirectional onboard charger using SiC MOSFETs.', partsUsed: ['SiC MOSFET WMT3N120', 'Gate Driver WGD220', 'Common-mode choke WE-CMB'],     companyName: 'Würth Elektronik', endorsed: true,  submittedAt: '2026-05-20T00:00:00Z', status: 'active'         },
  { id: 'si2', teamName: 'GreenGrid',  memberNames: ['Marcus Webb', 'Aisha Kamara'],                        projectTitle: 'Microgrid Controller for Campus Solar Array',            description: 'Embedded controller managing power flow between 40 kW rooftop solar and battery buffer.',    partsUsed: ['Toroidal Inductor WE-TI', 'EMI Filter WE-CLFS', 'DC-Link Capacitor'],          companyName: 'Würth Elektronik', endorsed: false, submittedAt: '2026-06-01T00:00:00Z', status: 'pending-review' },
  { id: 'si3', teamName: 'PulseDrive', memberNames: ['Lena Vogel', 'Tobias Müller', 'Yuki Tanaka', 'Fatima Al-Hassan'], projectTitle: 'Brushless Motor Driver for Autonomous Campus Shuttle', description: 'Three-phase BLDC drive system for a low-speed autonomous vehicle project.', partsUsed: ['Gate Driver WGD100', 'Power Inductor WE-PD4', 'Current Sense Resistor'], companyName: 'Würth Elektronik', endorsed: true,  submittedAt: '2026-04-15T00:00:00Z', status: 'active'         },
  { id: 'si4', teamName: 'StorEd',     memberNames: ['Kwame Asante', 'Priya Nair'],                         projectTitle: 'Modular 48V Battery Management System',                 description: 'Scalable BMS for lithium-iron-phosphate cell stacks with active balancing.',                partsUsed: ['Shunt Resistor WSLP', 'Ferrite Bead WE-CBF', 'NTC Thermistor'],                companyName: 'Würth Elektronik', endorsed: false, submittedAt: '2026-06-10T00:00:00Z', status: 'pending-review' },
  { id: 'si5', teamName: 'FluxLab',    memberNames: ['Anika Rao', 'Chen Wei', 'Marcus Webb'],               projectTitle: 'Wireless Power Transfer — 200W Qi2 Pad',                description: 'High-efficiency inductive power transfer pad reaching 93% efficiency at 200W.',             partsUsed: ['Wireless Charging Coil WE-WPCC', 'Resonant Capacitor', 'Shielding Foil'],      companyName: 'Würth Elektronik', endorsed: true,  submittedAt: '2026-03-28T00:00:00Z', status: 'completed'      },
];

// ─── Q&A Channels ─────────────────────────────────────────────────────────

export const MOCK_QA_CHANNELS: QAChannel[] = [
  { id: 'qa1', topic: 'Gate driver bootstrap supply — floating ground confusion',    course: 'EE401 — Power Electronics',      openQuestions: 3, participants: 18, lastActivityAt: '2026-06-19T22:10:00Z', tags: ['gate-driver', 'bootstrap', 'half-bridge'] },
  { id: 'qa2', topic: 'Lab 4 oscilloscope ringing — measurement artefact or real?', course: 'EE401 — Power Electronics',      openQuestions: 7, participants: 31, lastActivityAt: '2026-06-19T20:45:00Z', tags: ['lab', 'oscilloscope', 'ringing'] },
  { id: 'qa3', topic: 'SiC vs GaN for 48V-bus DC-DC — selection criteria',          course: 'EE501 — Power Systems Advanced', openQuestions: 2, participants:  9, lastActivityAt: '2026-06-18T16:00:00Z', tags: ['SiC', 'GaN', 'device-selection'] },
  { id: 'qa4', topic: 'Thermal pad placement for TO-247 packages on PCB',            course: 'EE401 — Power Electronics',      openQuestions: 4, participants: 14, lastActivityAt: '2026-06-17T11:30:00Z', tags: ['thermal', 'PCB', 'layout'] },
];

// ─── Student Deadlines ─────────────────────────────────────────────────────

export const MOCK_DEADLINES: Deadline[] = [
  { id: 'dl1', title: 'Lab 4 Report Submission',         type: 'lab-submission', dueAt: '2026-06-23T23:59:00Z', course: 'EE401 — Power Electronics', priority: 'high'   },
  { id: 'dl2', title: 'Carbon Footprint Calculator Bounty',type: 'bounty',       dueAt: '2026-07-20T23:59:00Z', linkedId: 'b3',                      priority: 'medium' },
  { id: 'dl3', title: 'EE401 Mid-term Project Proposal',  type: 'assignment',    dueAt: '2026-06-27T17:00:00Z', course: 'EE401 — Power Electronics', priority: 'high'   },
  { id: 'dl4', title: 'CI/CD Visualizer Widget Bounty',   type: 'bounty',        dueAt: '2026-07-15T23:59:00Z', linkedId: 'b1',                      priority: 'medium' },
  { id: 'dl5', title: 'VoltForge — Weekly Progress Check-in', type: 'project-review', dueAt: '2026-06-21T14:00:00Z',                               priority: 'low'    },
];

// ─── Communities ───────────────────────────────────────────────────────────

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'cm1',
    name: 'Power Electronics Society',
    description: 'The hub for students and professionals working on power conversion, motor drives, renewable energy integration, and high-voltage systems. Weekly paper reviews and lab share sessions.',
    category: 'research-club',
    memberCount: 842,
    tags: ['MOSFET', 'inverters', 'PFC', 'SiC', 'GaN', 'magnetics'],
    createdAt: '2024-01-10',
    isJoined: true,
    icon: '⚡',
    weeklyActivity: 34,
    isVerified: true,
  },
  {
    id: 'cm2',
    name: 'PCB Design Guild',
    description: 'Share your PCB layouts, get design-rule feedback, and discuss advanced topics like signal integrity, impedance control, and HDI stackups. Monthly gerber review nights.',
    category: 'study-group',
    memberCount: 521,
    tags: ['KiCad', 'Altium', 'signal-integrity', 'EMC', 'HDI'],
    createdAt: '2024-03-22',
    isJoined: false,
    icon: '🔌',
    weeklyActivity: 22,
    isVerified: true,
  },
  {
    id: 'cm3',
    name: 'Embedded & IoT Builders',
    description: 'From bare-metal RTOS to Linux on a Pi — this is the space for hands-on embedded developers. Share projects, debug sessions, and firmware tips.',
    category: 'open-source',
    memberCount: 1104,
    tags: ['STM32', 'RTOS', 'FreeRTOS', 'Linux', 'Zephyr', 'UART', 'SPI'],
    createdAt: '2023-11-05',
    isJoined: true,
    icon: '🤖',
    weeklyActivity: 58,
    isVerified: true,
  },
  {
    id: 'cm4',
    name: 'RF & Wireless Engineers',
    description: 'Antenna design, RF front-ends, spectrum analysis, Bluetooth/WiFi/5G. A technically focused group with a low tolerance for vague questions — come prepared.',
    category: 'research-club',
    memberCount: 318,
    tags: ['antenna', 'RF', 'spectrum', '5G', 'Bluetooth', 'Zigbee'],
    createdAt: '2024-05-01',
    isJoined: false,
    icon: '📡',
    weeklyActivity: 14,
  },
  {
    id: 'cm5',
    name: 'Würth Prototyping Circle',
    description: 'Exclusive to students using Würth Elektronik components through the academic access programme. Share designs, ask component questions, and get feedback from Würth engineers.',
    category: 'industry-connect',
    memberCount: 247,
    tags: ['Würth', 'components', 'prototyping', 'magnetics', 'gate-drivers'],
    createdAt: '2024-02-15',
    isJoined: true,
    icon: '🔧',
    weeklyActivity: 11,
    isVerified: true,
  },
  {
    id: 'cm6',
    name: 'Women in EE & Tech',
    description: 'A community for women and non-binary engineers in electrical engineering and related fields. Peer support, career advice, and celebrating wins — large and small.',
    category: 'mentorship-circle',
    memberCount: 389,
    tags: ['community', 'mentorship', 'career', 'inclusion'],
    createdAt: '2024-04-08',
    isJoined: false,
    icon: '💜',
    weeklyActivity: 19,
  },
  {
    id: 'cm7',
    name: 'EV & E-Mobility Hackers',
    description: 'Battery management systems, motor controllers, charging infrastructure, and vehicle-to-grid. If it moves electrons to move vehicles, it belongs here.',
    category: 'hackathon-team',
    memberCount: 673,
    tags: ['BMS', 'motor-control', 'V2G', 'SiC', 'CAN', 'EV'],
    createdAt: '2023-09-20',
    isJoined: true,
    icon: '🚗',
    weeklyActivity: 41,
    isVerified: true,
  },
  {
    id: 'cm8',
    name: 'AI Hardware Accelerators',
    description: 'FPGA, custom ASICs, GPU microarchitecture, and the hardware powering modern AI workloads. Deep technical discussions, paper reviews, and silicon bringup stories.',
    category: 'research-club',
    memberCount: 456,
    tags: ['FPGA', 'ASIC', 'GPU', 'HLS', 'Verilog', 'AI'],
    createdAt: '2024-06-01',
    isJoined: false,
    icon: '🧠',
    weeklyActivity: 27,
  },
];

// ─── Community Events ───────────────────────────────────────────────────────

export const MOCK_EVENTS: CommunityEvent[] = [
  {
    id: 'ev1',
    communityId: 'cm1',
    title: 'GaN vs SiC Selection Workshop',
    description: 'Interactive workshop comparing GaN and SiC devices for 48V-bus applications. Includes live simulation and a Q&A with Prof. Hartmann.',
    type: 'workshop',
    date: '2026-06-25T18:00:00Z',
    location: 'Online (Zoom)',
    attendeeCount: 87,
    maxAttendees: 120,
    tags: ['GaN', 'SiC', 'device-selection', 'workshop'],
    isRegistered: true,
  },
  {
    id: 'ev2',
    communityId: 'cm3',
    title: 'FreeRTOS Task Scheduling Deep Dive',
    description: 'A technical walkthrough of FreeRTOS task priorities, pre-emption, and common pitfalls. Live debugging session with a STM32 target board.',
    type: 'workshop',
    date: '2026-06-27T17:00:00Z',
    location: 'Online (Discord Stage)',
    attendeeCount: 142,
    maxAttendees: 200,
    tags: ['FreeRTOS', 'STM32', 'RTOS', 'debugging'],
    isRegistered: false,
  },
  {
    id: 'ev3',
    communityId: 'cm7',
    title: 'EV Battery Pack Design Hackathon',
    description: '48-hour virtual hackathon: design a 72V 20Ah pack for an electric cargo bike. Teams of 2–4. Judged on energy density, safety design, and cost estimate.',
    type: 'hackathon',
    date: '2026-07-05T09:00:00Z',
    location: 'Online (Async + Final Pitch Call)',
    attendeeCount: 56,
    maxAttendees: 80,
    tags: ['BMS', 'battery-design', 'hackathon', 'EV'],
    isRegistered: false,
  },
  {
    id: 'ev4',
    communityId: 'cm2',
    title: 'PCB Layout Review Night #12',
    description: 'Submit your PCB layout before the event; community members give structured, constructive feedback. All skill levels welcome.',
    type: 'networking',
    date: '2026-06-28T19:00:00Z',
    location: 'Online (Zoom)',
    attendeeCount: 33,
    tags: ['PCB', 'review', 'KiCad', 'Altium'],
    isRegistered: true,
  },
  {
    id: 'ev5',
    communityId: 'cm8',
    title: 'FPGA Acceleration for Neural Networks — Industry Talk',
    description: 'Engineer from Xilinx/AMD presents real-world FPGA deployment patterns for ML inference. Followed by open Q&A.',
    type: 'talk',
    date: '2026-07-02T16:00:00Z',
    location: 'Online (YouTube Live)',
    attendeeCount: 214,
    tags: ['FPGA', 'AI', 'inference', 'ML', 'industry'],
    isRegistered: false,
  },
  {
    id: 'ev6',
    communityId: 'cm5',
    title: 'Würth Components Office Hours',
    description: 'Monthly drop-in with Würth Elektronik application engineers. Bring your design questions, datasheet confusions, or component selection dilemmas.',
    type: 'networking',
    date: '2026-06-30T15:00:00Z',
    location: 'Online (Teams)',
    attendeeCount: 28,
    maxAttendees: 40,
    tags: ['Würth', 'office-hours', 'components', 'Q&A'],
    isRegistered: true,
  },
];

// ─── News Digest ───────────────────────────────────────────────────────────

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: 'nw1',
    title: 'TSMC Announces 1.4nm "A14" Process Node, Targeting Mass Production in 2028',
    summary: 'Taiwan Semiconductor Manufacturing Company has unveiled its next-generation 1.4nm process node, dubbed A14, featuring gate-all-around (GAA) transistor architecture. The company claims a 15% performance improvement and 30% power reduction over N2, with apple silicon and HPC clients expected to be first adopters.',
    source: 'EE Times',
    sourceLogoEmoji: '📰',
    category: 'semiconductors',
    publishedAt: '2026-06-20T07:00:00Z',
    readTime: 5,
    upvotes: 312,
    upvotedBy: ['u1', 'u3'],
    saved: false,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    url: 'https://eetimes.com/tsmc-a14',
    tags: ['TSMC', 'semiconductor', 'process-node', 'GAA', 'AI'],
  },
  {
    id: 'nw2',
    title: 'Infineon Launches CoolGaN 650V Devices Targeting Datacentre PSUs',
    summary: 'Infineon Technologies has expanded its CoolGaN portfolio with new 650V GaN transistors optimised for AC-DC power conversion in server power supply units. The devices achieve 99% efficiency at 12V bus voltage and are available in compact SMD packages suitable for high-density power stages.',
    source: 'Power Electronics News',
    sourceLogoEmoji: '⚡',
    category: 'power-electronics',
    publishedAt: '2026-06-20T06:30:00Z',
    readTime: 4,
    upvotes: 187,
    upvotedBy: ['u1', 'u7'],
    saved: true,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    url: 'https://powerelectronicsnews.com/infineon-coolgancol',
    tags: ['GaN', 'Infineon', 'power-electronics', 'datacenter', 'PSU'],
  },
  {
    id: 'nw3',
    title: 'Nordic Semi Unveils nRF54L Series: Ultra-Low-Power BLE 6.0 + Matter SoCs',
    summary: 'Nordic Semiconductor has announced the nRF54L series, the industry\'s first SoCs with Bluetooth LE 6.0 and native Matter support in a sub-mW active current envelope. The devices introduce a heterogeneous dual-core architecture pairing a 128MHz Arm Cortex-M33 with a dedicated Matter accelerator core.',
    source: 'Embedded Computing Design',
    sourceLogoEmoji: '🤖',
    category: 'iot-embedded',
    publishedAt: '2026-06-20T05:00:00Z',
    readTime: 6,
    upvotes: 241,
    upvotedBy: ['u1', 'u3', 'u7'],
    saved: false,
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    url: 'https://embeddedcomputing.com/nordic-nrf54l',
    tags: ['Nordic', 'BLE', 'Matter', 'IoT', 'SoC', 'ultra-low-power'],
  },
  {
    id: 'nw4',
    title: 'KiCad 9.0 Released: Differential Pair Router Overhaul and 3D STEP Export',
    summary: 'The KiCad EDA team has released version 9.0, featuring a completely rewritten differential pair router with length-matching tuning, push-and-shove improvements, and native STEP assembly export for full 3D manufacturing review. The update also brings a new constraint-driven DRC engine.',
    source: 'Hackaday',
    sourceLogoEmoji: '🔧',
    category: 'pcb-design',
    publishedAt: '2026-06-19T20:00:00Z',
    readTime: 3,
    upvotes: 528,
    upvotedBy: ['u2', 'u3', 'u7'],
    saved: true,
    imageUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80',
    url: 'https://hackaday.com/kicad-9',
    tags: ['KiCad', 'PCB', 'EDA', 'differential-pair', 'open-source'],
  },
  {
    id: 'nw5',
    title: 'Qualcomm X85 Modem Achieves 10 Gbps Peak 5G Download in FR2 mmWave Tests',
    summary: 'Qualcomm\'s Snapdragon X85 baseband has set a new commercial modem record, reaching 10.4 Gbps peak downlink throughput in millimetre-wave (FR2) testing. The device integrates advanced carrier aggregation across 8 mmWave carriers and is expected to debut in flagship smartphones Q3 2026.',
    source: 'Anandtech',
    sourceLogoEmoji: '📡',
    category: 'rf-wireless',
    publishedAt: '2026-06-19T16:00:00Z',
    readTime: 7,
    upvotes: 144,
    upvotedBy: ['u1'],
    saved: false,
    url: 'https://anandtech.com/qualcomm-x85',
    tags: ['Qualcomm', '5G', 'mmWave', 'RF', 'modem'],
  },
  {
    id: 'nw6',
    title: 'Bosch and Continental Partner on 800V Silicon Carbide Traction Inverter Platform',
    summary: 'Bosch Mobility and Continental AG have announced a joint development agreement for a shared 800V SiC traction inverter platform targeting mid-range EVs. The platform will use dual-sided liquid cooling and targets 98.5% peak efficiency, with SOP planned for 2028 across multiple OEM programmes.',
    source: 'Automotive Electronics',
    sourceLogoEmoji: '🚗',
    category: 'automotive',
    publishedAt: '2026-06-19T12:00:00Z',
    readTime: 5,
    upvotes: 203,
    upvotedBy: ['u1', 'u7'],
    saved: true,
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80',
    url: 'https://automotive-electronics.com/bosch-continental-sic',
    tags: ['SiC', 'traction-inverter', 'EV', 'automotive', '800V', 'Bosch'],
  },
  {
    id: 'nw7',
    title: 'Google TPU v6 "Trillium" Benchmarks Published: 5x Compute vs v4 per Chip',
    summary: 'Google has published detailed performance benchmarks for its sixth-generation Tensor Processing Unit, codenamed Trillium. The chips deliver 4.7x peak compute improvement and 2x memory bandwidth versus TPU v4, using a new systolic array architecture with in-package HBM3e and custom optical interconnects.',
    source: 'SemiAnalysis',
    sourceLogoEmoji: '🧠',
    category: 'ai-hardware',
    publishedAt: '2026-06-19T10:00:00Z',
    readTime: 9,
    upvotes: 476,
    upvotedBy: ['u1', 'u3'],
    saved: false,
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    url: 'https://semianalysis.com/google-tpu-v6',
    tags: ['Google', 'TPU', 'AI', 'accelerator', 'HBM', 'optical-interconnect'],
  },
  {
    id: 'nw8',
    title: 'EU Chips Act: €43B Fund Unlocks First Semiconductor Manufacturing Grants',
    summary: 'The European Commission has announced the first disbursement of grants under the EU Chips Act, totalling €8.2 billion directed at Intel\'s Magdeburg fab, TSMC\'s Dresden joint venture, and STMicroelectronics\' Crolles expansion. The grants aim to double Europe\'s semiconductor market share to 20% by 2030.',
    source: 'Reuters Technology',
    sourceLogoEmoji: '🌍',
    category: 'industry',
    publishedAt: '2026-06-18T14:00:00Z',
    readTime: 4,
    upvotes: 289,
    upvotedBy: ['u7'],
    saved: false,
    url: 'https://reuters.com/eu-chips-act-grants',
    tags: ['EU', 'Chips-Act', 'Intel', 'TSMC', 'STMicro', 'policy'],
  },
  {
    id: 'nw9',
    title: 'TI Releases High-Density LLC Resonant Controller with 99.2% Efficiency at 3.3 kW',
    summary: 'Texas Instruments has introduced the UCC256xxA series LLC resonant controller IC, capable of driving 3.3 kW LLC converters with 99.2% peak efficiency. The device integrates burst-mode control for light-load efficiency, adaptive dead-time optimisation, and protection features compliant with IEC 62368-1.',
    source: 'Power Electronics World',
    sourceLogoEmoji: '⚡',
    category: 'power-electronics',
    publishedAt: '2026-06-18T09:00:00Z',
    readTime: 5,
    upvotes: 158,
    upvotedBy: ['u7'],
    saved: true,
    url: 'https://powerelectronicsworld.com/ti-ucc256',
    tags: ['TI', 'LLC', 'resonant', 'controller', 'power-electronics', 'IEC'],
  },
  {
    id: 'nw10',
    title: 'Raspberry Pi Compute Module 5 Released with PCIe 3.0 and LPDDR5',
    summary: 'Raspberry Pi Ltd has launched the Compute Module 5 featuring the BCM2712 quad-core Cortex-A76 SoC, up to 8GB LPDDR5, 64GB eMMC, and a native PCIe 3.0 x1 lane. The CM5 targets industrial and embedded compute applications where the PCIe lane enables NVMe storage and custom peripheral attachment.',
    source: 'Tom\'s Hardware',
    sourceLogoEmoji: '🖥️',
    category: 'iot-embedded',
    publishedAt: '2026-06-17T15:00:00Z',
    readTime: 4,
    upvotes: 622,
    upvotedBy: ['u1', 'u2', 'u3'],
    saved: false,
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    url: 'https://tomshardware.com/rpi-cm5',
    tags: ['Raspberry-Pi', 'CM5', 'PCIe', 'LPDDR5', 'embedded'],
  },
  {
    id: 'nw11',
    title: 'Wolfspeed Opens World\'s Largest SiC Wafer Fab in Siler City, NC',
    summary: 'Wolfspeed has inaugurated its "The JP" mega-factory in Siler City, North Carolina — the world\'s largest dedicated SiC wafer manufacturing facility. The 445,000 sq ft facility targets 200mm wafer production at scale, supporting the explosive demand from EV traction, industrial motor drives, and grid infrastructure.',
    source: 'Power Systems Design',
    sourceLogoEmoji: '🏭',
    category: 'semiconductors',
    publishedAt: '2026-06-17T11:00:00Z',
    readTime: 6,
    upvotes: 334,
    upvotedBy: ['u7'],
    saved: false,
    imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    url: 'https://powersystemsdesign.com/wolfspeed-jp-factory',
    tags: ['Wolfspeed', 'SiC', 'manufacturing', 'wafer-fab', 'EV'],
  },
  {
    id: 'nw12',
    title: 'New IEC 61000-4-39 Standard Defines Conducted RF Immunity Test for EV Chargers',
    summary: 'The International Electrotechnical Commission has finalised IEC 61000-4-39, establishing standardised conducted RF immunity test procedures specifically for electric vehicle charging equipment. The standard covers conducted disturbances in the 150 kHz–30 MHz range and is mandatory for CE marking in the EU from 2027.',
    source: 'Compliance Engineering',
    sourceLogoEmoji: '📋',
    category: 'industry',
    publishedAt: '2026-06-16T08:00:00Z',
    readTime: 5,
    upvotes: 91,
    upvotedBy: [],
    saved: false,
    url: 'https://complianceengineering.com/iec-61000-4-39',
    tags: ['IEC', 'EMC', 'standard', 'EV-charger', 'RF-immunity', 'compliance'],
  },
];

export const getNewsById = (id: string): NewsArticle | undefined =>
  MOCK_NEWS.find(n => n.id === id);
